version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__SqlCon=server=db;port=3306;database=QuizDb;user=root;password=sero88256.!;  
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: QuizDb
      MYSQL_ROOT_PASSWORD: sero88256.!
    volumes:
      - mysqldata:/var/lib/mysql
    restart: always

  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
      - SERVERURL=5.175.136.193 
      - SERVERPORT=51820
      - PEERS=sero_laptop,sero_phone 
      - PEERDNS=auto
      - INTERNAL_NM=10.13.13.0 
    ports:
      - "51820:51820/udp" 
    volumes:
      - ./wireguard-config:/config
      - /lib/modules:/lib/modules
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    restart: always
    
volumes:
  mysqldata:
  